name: nsfw_detector_flutter
description: A Flutter package for detecting NSFW (Not Safe For Work) content in images using TensorFlow Lite. Easily integrate NSFW detection capabilities into your Flutter applications.
version: 1.0.2
homepage: https://github.com/hoyaaaa/nsfw_detector_flutter

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.4
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/nsfw.tflite

platforms:
  android:
  ios: