name: nsfw_detector_flutter
description: A Flutter package to detect NSFW (Not Safe For Work / NUDE / adults) contents and classify SAFE contents without downloading or setting any assets. Easily integrate NSFW into your Flutter applications.
version: 1.0.3
homepage: https://github.com/hoyaaaa/nsfw_detector_flutter

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: 
    git:
      url: https://github.com/tensorflow/flutter-tflite.git
      ref: main

  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/nsfw.tflite

platforms:
  android:
  ios: