name: nsfw_detector_flutter
description: A Flutter package to detect NSFW content in images.
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.9.0
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/nsfw.tflite
    - test/assets/nsfw.jpeg
    - test/assets/bikini.jpeg
    - test/assets/dress.jpeg